services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - MONGO_URI=<MONGO_URI>
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
